name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup uv + cache
      - uses: astral-sh/setup-uv@v5
      - name: Set up Python venv
        run: uv venv .venv
      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Ruff lint
        run: uv run ruff check .
      - name: Ruff format
        run: uv run ruff format --diff .

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
      - name: Set up Python venv
        run: uv venv .venv
      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Run tests
        run: uv run pytest

  docs:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v4

      # 2. Setup UV (or Python environment)
      - uses: astral-sh/setup-uv@v5

      - name: Create Python venv
        run: uv venv .venv

      # 3. Install dependencies (fresh install for reliability)
      - name: Install docs dependencies
        run: uv pip install --upgrade pip
      - run: uv pip install .[docs]

      # 4. Build Sphinx docs
      - name: Build HTML docs
        run: uv run sphinx-build -b html -a docs/ docs/_build/html

      # 5. Optional: check build output
      - name: List generated files
        run: ls -R docs/_build/html

      # 6. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          keep_files: false # optional: remove old files for clean deploy
