# Basic CI setup: Lint with ruff, run tests with pytest, deploy coverage to GitHub Pages
name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Ruff lint
        run: uv run ruff check .
      - name: Ruff format
        run: uv run ruff format --diff .

  test:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Run tests
        run: uv run pytest

  coverage:
    name: Coverage Report
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Install test dependencies
        run: |
          uv pip install pytest pytest-cov
      - name: Run pytest with coverage
        run: uv run pytest --cov=pybbtd --cov-report=html tests/
      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v3
        with:
          name: htmlcov
          path: htmlcov/

  coverage-deploy:
    name: Deploy Coverage Report to GitHub Pages
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - name: Install test dependencies (system-wide)
        run: |
          uv pip install --system pytest pytest-cov

      - name: Run pytest with coverage
        run: uv run pytest --cov=pybbtd --cov-report=html tests/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./htmlcov
