# Basic CI setup: Lint with ruff, run tests with pytest
name: Test

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Ruff lint
        run: uv run ruff check .
      - name: Ruff format
        run: uv run ruff format --diff .

  test:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5

      # Run tests
      - name: Run tests
        run: uv run pytest

  # code-cov:
  #   name: Check coverage with CodeCov
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: codecov/codecov-action@v5
  #       with:
  #         file: ./coverage.xml
  #         verbose: true
